### ISSUE TITLE
Decoding issue 

### ISSUE THREAD

**Issue by saroar** [pointfreeco/swift-url-routing#45] opened 2022-08-29 14:44 UTC
My playground code which dont have any issue 
playground code here https://gist.github.com/saroar/a1bab728f4292c54cb76085a633c6a3c
my client iOS app dont send any request to server becz its not decoding my query 
https://github.com/AddaMeSPB/AddaMeIOS/blob/siteRouter/AddameSPM/Sources/EventView/EventsReducer.swift#L112
error coming from decoding from this 
https://github.com/pointfreeco/swift-url-routing/blob/main/Sources/URLRouting/Client/Client.swift#L53

```swift
HTTPRequest.HRError(
        description: "fetch events get error",
        reason: URLRoutingDecodingError(
          bytes: Data(35 bytes),
          response: NSHTTPURLResponse(),
          underlyingError: DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: [],
              debugDescription: "The given data was not valid JSON.",
              underlyingError: NSError(
                domain: "NSCocoaErrorDomain",
                code: 3840,
                userInfo: [
                  "NSDebugDescription": "Invalid value around line 1, column 0.",
                  "NSJSONSerializationErrorIndex": 0
                ]
              )
            )
          )
        )
      )
```

**Comment by saroar** [comment] 2022-08-30 05:51
<img width="1163" alt="Screenshot 2022-08-30 at 08 45 59" src="https://user-images.githubusercontent.com/8770772/187359801-13300b30-6d82-42b0-99b1-7415c580ed75.png">

**Comment by stephencelis** [comment] 2022-09-08 21:42
@saroar It looks like the server is sending back a "deadline exceeded" error, which is why decoding is failing.

You can see the definition here:

https://github.com/swift-server/async-http-client/blob/7f998f5118de081fa2034833ce95bb5925dc6459/Sources/AsyncHTTPClient/HTTPClient.swift#L1181-L1182

I'm not familiar with this error or how to work around it, but I don't think it's a bug with our library. Can you ask someone in a community more familiar with the `HTTPClient` library, and whatever server code you are using to serve up that response? They may be able to help you debug. If it turns out to be an issue with our library we'd be happy to address! We just need a reproduction.

Since this doesn't appear to be a bug in our library, I'm going to close it. But if you do believe there's a bug in our library, please file a new issue with a reproduction for us to work with and instructions on how to reproduce. Without steps to reproduce, we really don't have much of an ability to try to fix.

**Closed by stephencelis** 2022-09-08 21:42 UTC
